name: Example workflow for Maven using Snyk
on:
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: RunSnyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Generate Snyk Report
        run: npx snyk test --json > snyk-report.json

      - name: Save Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: snyk-report
          path: snyk-report.json

      - name: Download math result for job 1
        uses: actions/download-artifact@v3
        with:
          name: snyk-reports
      - shell: bash
        run: |
          cat snyk-report.json   
