name: Snyk Security Scan and Report
 
on:

 workflow_dispatch:
 
jobs:
  security_scan_and_report:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Run Snyk to check for vulnerabilities
        run: |
          # Install Snyk CLI
          npm install -g snyk
          # Authenticate with Snyk using token
          snyk auth ${{ secrets.SNYK_TOKEN }}
          # Run Snyk to generate the scan report in JSON format
          snyk test  --json > scan_report.json
          cat scan_report.json
