name: Example workflow for Maven using Snyk
on:
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: RunSnyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor  

  notify-slack:
    runs-on: ubuntu-latest
    needs: security
    steps:
      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ needs.security.outcome }}
          text: |
            Snyk scan completed with status: ${{ needs.security.outcome }}.
            See details in the [workflow run](${{ github.event.workflow_run_url }}).
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          




