name: Example workflow for Maven using Snyk
on:
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: RunSnyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Generate Snyk Report
        run: npx snyk test --json > snyk-report.json

      - name: Save Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: snyk-report
          path: snyk-report.json   
