name: Example workflow for Maven using Snyk
on:
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: RunSnyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif    

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: "./build/"  

      - name: Download Build
        uses: actions/download-artifact@v2
        with:
          name: report
          path: path/to/artifact/world.txt   
          
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
